name: composite-action

on: 
  workflow_dispatch

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: luumarodrigues/composite-action@master
        with:
          who-to-greet: 'Maria'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
