name:  cicd-webapp

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    
env:
  AZURE_WEBAPP_NAME: ${{ env.AZURE_WEBAPP_NAME }}
    
jobs:
  CI:
    uses: luumarodrigues/SRE.Templates/.github/workflows/build-dotnet.yml@master
    with:
      buildConfiguration: Release
      
  CD:
    uses: luumarodrigues/SRE.Templates/.github/workflows/deploy-webapp.yml@master
    needs: CI
    with:
      environment: 'dev'
      app-name: ${{ env.AZURE_WEBAPP_NAME }}
    secrets:
      publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
      
