name:  cicd-webapp

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  
jobs:
  CI:
    uses: luumarodrigues/SRE.Templates/.github/workflows/build-dotnet.yml@master
    with:
      buildConfiguration: Release
      
  CD:
    uses: luumarodrigues/SRE.Templates/.github/workflows/deploy-webapp.yml@master
    needs: CI
    with:
      environment: 'prod'
      app-name: 'teste'
    secrets:
      publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
