name:  cicd-webapp

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  
jobs:
  CI:
    uses: luumarodrigues/SRE.Templates/.github/workflows/build-dotnet.yml@master
    with:
      buildConfiguration: Release
    permissions: 
      actions: write
      
  CD-dev:
    uses: luumarodrigues/SRE.Templates/.github/workflows/deploy-webapp.yml@master
    needs: CI
    with:
      environment: 'dev'
    secrets: inherit
      
  CD-prod:
    uses: luumarodrigues/SRE.Templates/.github/workflows/deploy-webapp.yml@master
    needs: [CI, CD-dev]
    with:
      environment: 'prod'
    secrets: inherit
