name: webapp-sample

on: 
  workflow_dispatch:
    
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.2.0
          
      - name: Install dependencies
        run: dotnet restore
        
      - name: Build WebApi
        run: dotnet build --configuration Release --no-restore
        
      - name: Publish
        run: dotnet publish -c Release -o ./output
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: webapp
          path: output
          
  deploy:
    needs: build
    name: Deploy
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.1.1
      with:
        name: webapp
        path: output
        
    - name: 'Run Azure webapp deploy'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: './output'
